# EXAMPLE CONFIGURATION FILE
spring.application.name=BankingApi

# DB
spring.datasource.url=jdbc:postgresql://localhost:5435/banking_db
spring.datasource.username=postgres
spring.datasource.password=your_password

spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=10

# Hibernate
spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=your_super_secret_jwt_key_min_32_chars
jwt.expiration=3600000

# Errors
spring.web.error.include-message=always

# Logging
logging.level.org.springframework.web=DEBUG

# Jackson
spring.jackson.deserialization.fail-on-unknown-properties=true

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true